version: '3.8'

services:
  coworking-servers-configurator:
    build: 'source/servers_configurator/python'
    depends_on:
      - coworking-kafka
      - coworking-database-configurator
    ports:
      - '8000:80'
    networks:
      - coworking-network

  coworking-database-configurator:
    build: 'source/database_configurator/python'
    depends_on:
      - coworking-kafka
      - coworking-database
    ports:
      - '8001:80'
    networks:
      - coworking-network

  coworking-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - coworking-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://coworking-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
    networks:
      - coworking-network

  coworking-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - coworking-network
  
  coworking-database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    networks:
      - coworking-network  

volumes:
  postgres_data:

networks:
  coworking-network:
    driver: bridge
