version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: coworking-zookeeper:1.0.0
    ports:
      - '2181:2181'
    networks:
      - coworking-network

  kafka:
    container_name: kafka
    image: coworking-kafka:1.0.0
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - coworking-network

networks:
  coworking-network:
    driver: host
